### ISSUE TITLE
ShowTcg1EventLogs () while advancement is off by 1

### ISSUE THREAD

**Issue by apop2** [jiazhang0/efi-tpm2-utils#1]
TCG_PCR_EVENT contains 1 byte of Event data. Event size is the total amount of event data, and the advance statement does not take this into account.

Event = (TCG_PCR_EVENT *)((UINT8 *)(Event + 1) + Event->EventSize);
should be
Event = (TCG_PCR_EVENT *)((UINT8 *)(Event + 1) + Event->EventSize - 1);

**Comment by jiazhang0** [comment]
@apop2 Sorry I missed this for a while. I will fix it. Thanks for reporting the issue.

**Comment by jiazhang0** [comment]
@apop2 The fix https://github.com/jiazhang0/efi-tpm2-utils/commit/2e83fc3191f50b320d111d9b0672743f5e3e8626 is merged. Thanks for reporting this issue.
